replicaCount: 3

image:
  repository: redis
  tag: "6.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

tls:
  certSecret: "redis-tls-secret"
  configMapName: "redis-config"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

