replicaCount: 1

image:
  repository: redis
  tag: "6.2.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379


resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}

