apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.tls.configMapName }}
data:
  redis.conf: |
    tls-port 6379
    port 0
    tls-cluster yes
    tls-cert-file /certs/redis.crt
    tls-key-file /certs/redis.key
    tls-ca-cert-file /certs/ca.crt
    # tls-auth-clients no
    # protected-mode no
    cluster-enabled yes
    cluster-config-file /tmp/nodes.conf
    cluster-node-timeout 5000

