apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.certSecret }}
type: Opaque
data:
  redis.crt: {{ .Files.Get "certs/redis.crt" | b64enc }}
  redis.key: {{ .Files.Get "certs/redis.key" | b64enc }}
  ca.crt: {{ .Files.Get "certs/ca.crt" | b64enc }}

