apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  labels:
    app: {{ include "redis.name" . }}
data:
  redis.conf: |-
    bind 0.0.0.0
    protected-mode no
    dir /data
    # Додаткові налаштування Redis

